### ISSUE TITLE
schema

### ISSUE THREAD

**Issue by gerisse** [SensorsIot/Weight-Sensors#1]
Hi Mr Spiess
First, congratulations for all your shared videos : it s great.
a question about this project , ESP32_IKEA : i dont understand how connect the wires of the ikea scale.
With the wheastone bridge, black and red wires connect sensors directly 2 to 2, only whites wires are connecting to the input of hx711 : no need to put power directly on sensors ?
if you have a schema, it would be fine.
Thanks from Mulhouse

**Comment by SensorsIot** [comment]
I hope you figured it out since then. Sorry.
